name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Perform tasks
      run: |
        # Add commands to perform tasks here

    - name: Commit and push if changes
      run: |
        git config --global user.name 'tkfka1'
        git config --global user.email 'tkfka1@korea.com'
        git add .
        git commit -m "Daily update"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
